/* One-line teaching points, in question order. Key page only. */
window.RATIONALES = {
  senior: [
    "Hypovolaemia kills before the airway does. Resuscitate, then rapid sequence induction with a reduced dose, two suctions and a tube half a size smaller for the oedematous airway.",
    "Fire triangle: FiO2 below 0.3 in air, no nitrous oxide (it supports combustion), a laser-resistant tube, and the cuff filled with saline dyed with methylene blue so a hit is obvious.",
    "Remove fuel and oxidiser first — tube out, gases off, saline into the field. Then mask ventilate, re-intubate and bronchoscope to assess the damage.",
    "Real-time bronchoscopy confirms midline needle entry between the tracheal rings and prevents posterior wall perforation and paratracheal placement.",
    "TIVA with remifentanil plus a 15 degree head-up tilt lowers venous pressure at the field. Hypercapnia and deep volatile both worsen bleeding; head-down is exactly wrong.",
    "Once the trachea is divided the surgeon passes a sterile armoured tube into the distal stump and the circuit is handed over the drapes. Check the connection is secure before the oral tube is withdrawn.",
    "Juvenile nasopharyngeal angiofibroma is a highly vascular tumour of adolescent boys. Embolise 24–48 hours beforehand, two large cannulae, arterial line, cross-matched blood in theatre.",
    "Keep spontaneous ventilation and induce with a volatile in theatre, surgeon scrubbed for a front-of-neck airway. A relaxant risks can't intubate, can't oxygenate.",
    "Transoesophageal echo detects as little as 0.02 ml/kg of air, ahead of precordial Doppler. A falling end-tidal CO2 is a later and less specific sign.",
    "Stop entrainment and stop the bubble expanding: flood the field, nitrous oxide off, 100% oxygen. Then jugular compression, head-down left lateral, and aspirate from a right atrial catheter.",
    "Motor evoked potentials need TIVA. Volatiles depress the anterior horn cell synapse dose-dependently and neuromuscular blockade abolishes the recorded response.",
    "Brain Trauma Foundation: CPP 60–70 mmHg, systolic at or above 100 mmHg for ages 50–69 and 110 otherwise. Prophylactic hyperventilation causes ischaemia.",
    "Posterior ischaemic optic neuropathy — long prone cases, blood loss, hypotension and large crystalloid volumes. The fundus looks normal at first, which delays the diagnosis.",
    "Seven nerves each side: supraorbital, supratrochlear, zygomaticotemporal, auriculotemporal, greater and lesser occipital, and greater auricular. Miss one and the pins hurt.",
    "Prevertebral swelling or haematoma at 6–12 hours obstructs the airway. Recurrent laryngeal palsy and dysphagia follow. Keep a difficult airway trolley at the bedside.",
    "Propofol and benzodiazepines suppress tremor and alter neuronal firing patterns. Low-dose dexmedetomidine or a fully awake technique preserves the recording.",
    "Restore perfusion and remove the mechanical insult: raise MAP above 80, ask for the distraction to be relaxed, check haematocrit, temperature and anaesthetic depth, then consider a wake-up test.",
    "Depth is roughly 12 cm plus height in cm divided by 10 — about 29 cm at the teeth for a 170 cm adult. Auscultation alone misses up to a third of malpositions, so confirm fibreoptically.",
    "Malposition is the commonest cause. FiO2 1.0 and a fibreoptic check first, then recruit the dependent lung, add PEEP to it and CPAP 5 to the non-dependent lung.",
    "Hypoxic pulmonary vasoconstriction diverts blood from the collapsed lung. Volatiles above 1 MAC, glyceryl trinitrate, nitroprusside, dobutamine and high pulmonary artery pressures all blunt it.",
    "Post-pneumonectomy pulmonary oedema: the remaining lung receives the entire cardiac output. Keep total fluid under about 2 litres in the first 24 hours and use vasopressors rather than volume.",
    "Paravertebral block matches epidural analgesia after thoracotomy with less hypotension, urinary retention, nausea and fewer failed blocks — and it can be placed under direct vision by the surgeon.",
    "Isolate before you ventilate. Positive pressure through a fistula loses tidal volume and spills infected material into the healthy lung.",
    "Insufflation above 10 mmHg reduces venous return and shifts the mediastinum, giving hypotension and desaturation. Ask the surgeon to drop the pressure rather than chasing it with fluid.",
    "Myasthenia gravis leaves fewer functional acetylcholine receptors: profound sensitivity to non-depolarisers and relative resistance to suxamethonium. Use quantitative neuromuscular monitoring throughout."
  ],
  junior: [
    "Postoperative nausea and vomiting affects up to a third of children after tonsillectomy. Dexamethasone plus ondansetron should be routine.",
    "Children with obstructive sleep apnoea desaturate on standard opioid doses. Halve the dose and titrate, and lean on paracetamol, an NSAID and dexamethasone.",
    "An oral RAE tube sits out of the surgeon's field and the cuff protects the larynx from blood.",
    "If a pack is used it goes on the swab count, is declared at the WHO check, and must be removed and confirmed before extubation. Retained packs kill.",
    "The child is hypovolaemic from loss that has been hidden, and has a stomach full of blood. Resuscitate first, then rapid sequence induction with suction ready.",
    "Blood tracks down the oesophagus, so what is seen is a fraction of what has been lost. Judge by heart rate, capillary refill and postural change, not the sheets.",
    "Nitrous oxide diffuses into the middle ear faster than nitrogen leaves and can lift the graft. Stop it well before graft placement, or avoid it altogether.",
    "Facial nerve monitoring needs an unparalysed patient. Intubate with a short-acting agent, or with none, and maintain with volatile or TIVA.",
    "A five-minute case: supraglottic airway, spontaneous ventilation, paracetamol and ibuprofen. Opioids are rarely needed and delay discharge.",
    "Keep spontaneous ventilation so positive pressure cannot drive the peanut distally. Inhalational induction, deep plane, topical lidocaine to the cords, surgeon present throughout.",
    "Any swallowed foreign body means a full stomach. Rapid sequence induction with a cuffed tube protects the lungs while the rigid scope shares the airway.",
    "Epiglottitis: no cannula, no tongue depressor, no lying flat, no separation from the parent. Inhalational induction in theatre with ENT scrubbed and a tube a size or two small.",
    "Blood pools behind the soft palate. Suction the pharynx under direct vision, then extubate awake, or deeply in the lateral head-down position.",
    "Low inspired oxygen, no nitrous oxide, a laser-resistant tube, wet pledgets around the cuff, and saline in the field. Oxygen is the fuel.",
    "An immature tract collapses and a blind push creates a false passage. Oxygenate over the mouth and over the stoma, call for help, and follow the emergency tracheostomy algorithm.",
    "Packs abolish the nasal airway and swallowed blood provokes vomiting. Give anti-emetics, extubate awake, and warn the patient they will have to mouth breathe.",
    "Normal intracranial pressure is 5–15 mmHg. Sustained pressure above 20–25 mmHg needs treatment.",
    "CPP = MAP − ICP, using central venous pressure instead if it exceeds ICP. Autoregulation holds flow steady between roughly 50 and 150 mmHg.",
    "Mannitol 0.25–1 g/kg draws water across an intact blood–brain barrier. Hypertonic saline is the alternative; watch the sodium and the urine output.",
    "Hypercapnia dilates cerebral vessels and raises cerebral blood flow and ICP. Hypocapnia, a head-up tilt and propofol all lower it.",
    "15–30 degrees head-up, neck neutral, tapes rather than ties. Anything that obstructs jugular drainage raises intracranial pressure.",
    "Infants have little thermal reserve and the tunnelling exposes a long surface. The shunt is being placed for raised pressure, so induction must be smooth.",
    "Blunt the pressor response: adequate opioid, propofol, full relaxation before laryngoscopy, and treat hypotension early — perfusion depends on it.",
    "A compressed abdomen raises inferior vena caval pressure, so blood returns through engorged epidural veins and the surgical field bleeds. Use proper prone supports.",
    "An extradural haematoma with a lucid interval is a surgical emergency. Every minute of hypoxia or hypotension worsens the outcome — get the patient to theatre."
  ]
};
